/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.myhotel.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

import cn.myhotel.model.Admins;
import cn.myhotel.model.AdminsDAO;

/** 
 * MyEclipse Struts
 * 
 * XDoclet definition:
 * @struts.form name="addadminForm"
 */
public class AddadminForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = -3454339553010546676L;

	/** adminId property */
	private String adminId;

	/** name property */
	private String name;

	/** pop property */
	private String pop;

	/** password property */
	private String password;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		if(request.getParameter("id")!=null)
		{
			AdminsDAO dao = new AdminsDAO();
			Admins admin = dao.findById(Long.valueOf(request.getParameter("id")));
			try{
				BeanUtils.copyProperties(this,admin);
			}catch(Exception e){
				e.printStackTrace();
			}
			dao.closeSession();
			request.setAttribute("admininfo", admin);
		}
		else
		{
			name = null;
			adminId = null;
			password = "123456";
			pop = "0";
		}
	}

	/** 
	 * Returns the adminId.
	 * @return String
	 */
	public String getAdminId() {
		return adminId;
	}

	/** 
	 * Set the adminId.
	 * @param adminId The adminId to set
	 */
	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the pop.
	 * @return String
	 */
	public String getPop() {
		return pop;
	}

	/** 
	 * Set the pop.
	 * @param pop The pop to set
	 */
	public void setPop(String pop) {
		this.pop = pop;
	}

	/** 
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}