/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.myhotel.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

import cn.myhotel.model.Badman;
import cn.myhotel.model.BadmanDAO;

/** 
 * MyEclipse Struts
 * 
 * XDoclet definition:
 * @struts.form name="addbadmanForm"
 */
public class AddbadmanForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 7790625427108196762L;

	/** sex property */
	private String sex;

	/** name property */
	private String name;

	/** cardno property */
	private String cardno;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		if(request.getParameter("id")!=null)
		{
			BadmanDAO dao = new BadmanDAO();
			Badman badman = dao.findById(Long.valueOf(request.getParameter("id")));
			try{
				BeanUtils.copyProperties(this,badman);
			}catch(Exception e){
				e.printStackTrace();
			}
			
			dao.closeSession();
			request.setAttribute("badman", badman);
		}
		else
		{
			name = null;
			sex = "ÄÐ";
			cardno = null;
		}
	}

	/** 
	 * Returns the sex.
	 * @return String
	 */
	public String getSex() {
		return sex;
	}

	/** 
	 * Set the sex.
	 * @param sex The sex to set
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the cardno.
	 * @return String
	 */
	public String getCardno() {
		return cardno;
	}

	/** 
	 * Set the cardno.
	 * @param cardno The cardno to set
	 */
	public void setCardno(String cardno) {
		this.cardno = cardno;
	}
}