/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.myhotel.struts.form;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

import cn.myhotel.model.Room;
import cn.myhotel.model.RoomDAO;

/** 
 * MyEclipse Struts
 * 
 * XDoclet definition:
 * @struts.form name="addorder2Form"
 */
public class Addorder2Form extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = -3048938838325222783L;

	/** sex property */
	private String sex;

	/** price property */
	private String price;

	/** address property */
	private String address;

	/** tel property */
	private String tel;

	/** name property */
	private String name;

	/** roomId property */
	private String roomId;

	/** cardno property */
	private String cardno;

	/** date1 property */
	private String date1;

	/** datenum property */
	private String datenum;
	
	private List roomInfo = new ArrayList();

	/*
	 * Generated Methods
	 */

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		name = null;
		sex = "ÄÐ";
		date1 = null;
		cardno = null;
		tel = null;
		address = null;
		datenum = "1";
		price = null;
		roomId = null;
		RoomDAO dao = new RoomDAO();
		List list = dao.getSession().createQuery("from Room where isused = '0'").list();
		for(int i=0;i<list.size();i++)
		{
			Room room = (Room)list.get(i);
			String str = room.getRoomId() + "--" + room.getRoomtype().getTypename() + "--" + room.getRoomtype().getPrice().toString();
			room.setRoomId(str);
			roomInfo.add(room);
		}
		roomInfo.add(0, new Room());
		dao.closeSession();
	}

	/** 
	 * Returns the sex.
	 * @return String
	 */
	public String getSex() {
		return sex;
	}

	/** 
	 * Set the sex.
	 * @param sex The sex to set
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/** 
	 * Returns the price.
	 * @return String
	 */
	public String getPrice() {
		return price;
	}

	/** 
	 * Set the price.
	 * @param price The price to set
	 */
	public void setPrice(String price) {
		this.price = price;
	}

	/** 
	 * Returns the address.
	 * @return String
	 */
	public String getAddress() {
		return address;
	}

	/** 
	 * Set the address.
	 * @param address The address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/** 
	 * Returns the tel.
	 * @return String
	 */
	public String getTel() {
		return tel;
	}

	/** 
	 * Set the tel.
	 * @param tel The tel to set
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the roomId.
	 * @return String
	 */
	public String getRoomId() {
		return roomId;
	}

	/** 
	 * Set the roomId.
	 * @param roomId The roomId to set
	 */
	public void setRoomId(String roomId) {
		this.roomId = roomId;
	}

	/** 
	 * Returns the cardno.
	 * @return String
	 */
	public String getCardno() {
		return cardno;
	}

	/** 
	 * Set the cardno.
	 * @param cardno The cardno to set
	 */
	public void setCardno(String cardno) {
		this.cardno = cardno;
	}

	/** 
	 * Returns the date1.
	 * @return String
	 */
	public String getDate1() {
		return date1;
	}

	/** 
	 * Set the date1.
	 * @param date1 The date1 to set
	 */
	public void setDate1(String date1) {
		this.date1 = date1;
	}

	/** 
	 * Returns the datenum.
	 * @return String
	 */
	public String getDatenum() {
		return datenum;
	}

	/** 
	 * Set the datenum.
	 * @param datenum The datenum to set
	 */
	public void setDatenum(String datenum) {
		this.datenum = datenum;
	}
	
	public List getRoomInfo(){
		return roomInfo;
	}
	
	public void setRoomInfo(List roomInfo){
		this.roomInfo = roomInfo;
	}
}