/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.myhotel.struts.form;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

import cn.myhotel.model.Room;
import cn.myhotel.model.RoomDAO;
import cn.myhotel.model.Roomtype;

/** 
 * MyEclipse Struts
 * 
 * XDoclet definition:
 * @struts.form name="addroomForm"
 */
public class AddroomForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 2733973047524284565L;

	/** floor property */
	private String floor;

	/** roomId property */
	private String roomId;

	/** typeId property */
	private String typeId;
	
	private List typeInfo = new ArrayList();

	/*
	 * Generated Methods
	 */

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		RoomDAO dao = new RoomDAO();
		if(request.getParameter("id")!=null)
		{
			Room room = dao.findById(Long.valueOf(request.getParameter("id")));
			try{
				BeanUtils.copyProperties(this,room);
			}catch(Exception e){
				e.printStackTrace();
			}
			
			if(room.getRoomtype()!=null)
			    this.typeId = room.getRoomtype().getId().toString();
			typeInfo = dao.getSession().createQuery("from Roomtype").list();
			typeInfo.add(0, new Roomtype());
			
			dao.closeSession();
			request.setAttribute("room", room);
		}
		else
		{
			roomId = null;
			typeId = null;
			floor = "1";
			
			
			typeInfo = dao.getSession().createQuery("from Roomtype").list();
			typeInfo.add(0, new Roomtype());
			
			dao.closeSession();
		}
	}

	/** 
	 * Returns the floor.
	 * @return String
	 */
	public String getFloor() {
		return floor;
	}

	/** 
	 * Set the floor.
	 * @param floor The floor to set
	 */
	public void setFloor(String floor) {
		this.floor = floor;
	}

	/** 
	 * Returns the roomId.
	 * @return String
	 */
	public String getRoomId() {
		return roomId;
	}

	/** 
	 * Set the roomId.
	 * @param roomId The roomId to set
	 */
	public void setRoomId(String roomId) {
		this.roomId = roomId;
	}

	/** 
	 * Returns the typeId.
	 * @return String
	 */
	public String getTypeId() {
		return typeId;
	}

	/** 
	 * Set the typeId.
	 * @param typeId The typeId to set
	 */
	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}
	
	public List getTypeInfo(){
		return typeInfo;
	}
	
	public void setTypeInfo(List typeInfo){
		this.typeInfo = typeInfo;
	}
}