/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.myhotel.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

import cn.myhotel.model.Client;
import cn.myhotel.model.ClientDAO;

/** 
 * MyEclipse Struts
 * 
 * XDoclet definition:
 * @struts.form name="ediclientForm"
 */
public class EdiclientForm extends ValidatorForm {
	/**
	 * 
	 */
	private static final long serialVersionUID = 9123398202569497148L;
	/*
	 * Generated fields
	 */

	/** isused property */
	private String isused;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		String id = request.getParameter("id");
		ClientDAO dao = new ClientDAO();
		Client client = dao.findById(Long.valueOf(id));
		this.isused = client.getIsused();
		request.setAttribute("client", client);
	}

	/** 
	 * Returns the isused.
	 * @return String
	 */
	public String getIsused() {
		return isused;
	}

	/** 
	 * Set the isused.
	 * @param isused The isused to set
	 */
	public void setIsused(String isused) {
		this.isused = isused;
	}
}