package cn.myhotel.model;

import java.util.Date;


/**
 * AbstractOrder1 generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractOrder1  implements java.io.Serializable {


    // Fields    

     private Long id;
     private Room room;
     private Client client;
     private Date regdate;
     private Double price;
     private Integer datenum;
     private String isused;
     private String done;


    // Constructors

    /** default constructor */
    public AbstractOrder1() {
    }

	/** minimal constructor */
    public AbstractOrder1(Room room, Client client, Date regdate, Double price, Integer datenum) {
        this.room = room;
        this.client = client;
        this.regdate = regdate;
        this.price = price;
        this.datenum = datenum;
    }
    
    /** full constructor */
    public AbstractOrder1(Room room, Client client, Date regdate, Double price, Integer datenum, String isused, String done) {
        this.room = room;
        this.client = client;
        this.regdate = regdate;
        this.price = price;
        this.datenum = datenum;
        this.isused = isused;
        this.done = done;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public Room getRoom() {
        return this.room;
    }
    
    public void setRoom(Room room) {
        this.room = room;
    }

    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

    public Date getRegdate() {
        return this.regdate;
    }
    
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }

    public Integer getDatenum() {
        return this.datenum;
    }
    
    public void setDatenum(Integer datenum) {
        this.datenum = datenum;
    }

    public String getIsused() {
        return this.isused;
    }
    
    public void setIsused(String isused) {
        this.isused = isused;
    }

    public String getDone() {
        return this.done;
    }
    
    public void setDone(String done) {
        this.done = done;
    }
   








}