package cn.myhotel.model;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractRoomtype generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractRoomtype  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String typename;
     private Double price;
     private Set rooms = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractRoomtype() {
    }

	/** minimal constructor */
    public AbstractRoomtype(String typename) {
        this.typename = typename;
    }
    
    /** full constructor */
    public AbstractRoomtype(String typename, Double price, Set rooms) {
        this.typename = typename;
        this.price = price;
        this.rooms = rooms;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getTypename() {
        return this.typename;
    }
    
    public void setTypename(String typename) {
        this.typename = typename;
    }

    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }

    public Set getRooms() {
        return this.rooms;
    }
    
    public void setRooms(Set rooms) {
        this.rooms = rooms;
    }
   








}