package cn.myhotel.model;



/**
 * AbstractAdmins generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractAdmins  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String adminId;
     private String password;
     private String name;
     private String pop;
     private String type;


    // Constructors

    /** default constructor */
    public AbstractAdmins() {
    }

	/** minimal constructor */
    public AbstractAdmins(String adminId, String password, String name, String type) {
        this.adminId = adminId;
        this.password = password;
        this.name = name;
        this.type = type;
    }
    
    /** full constructor */
    public AbstractAdmins(String adminId, String password, String name, String pop, String type) {
        this.adminId = adminId;
        this.password = password;
        this.name = name;
        this.pop = pop;
        this.type = type;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getPop() {
        return this.pop;
    }
    
    public void setPop(String pop) {
        this.pop = pop;
    }

    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
   








}