package cn.myhotel.model;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractRoom generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractRoom  implements java.io.Serializable {


    // Fields    

     private Long id;
     private Roomtype roomtype;
     private String roomId;
     private Integer floor;
     private String isused;
     private Set order2s = new HashSet(0);
     private Set order1s = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractRoom() {
    }

	/** minimal constructor */
    public AbstractRoom(Roomtype roomtype, String roomId, Integer floor) {
        this.roomtype = roomtype;
        this.roomId = roomId;
        this.floor = floor;
    }
    
    /** full constructor */
    public AbstractRoom(Roomtype roomtype, String roomId, Integer floor, String isused, Set order2s, Set order1s) {
        this.roomtype = roomtype;
        this.roomId = roomId;
        this.floor = floor;
        this.isused = isused;
        this.order2s = order2s;
        this.order1s = order1s;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public Roomtype getRoomtype() {
        return this.roomtype;
    }
    
    public void setRoomtype(Roomtype roomtype) {
        this.roomtype = roomtype;
    }

    public String getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }

    public Integer getFloor() {
        return this.floor;
    }
    
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    public String getIsused() {
        return this.isused;
    }
    
    public void setIsused(String isused) {
        this.isused = isused;
    }

    public Set getOrder2s() {
        return this.order2s;
    }
    
    public void setOrder2s(Set order2s) {
        this.order2s = order2s;
    }

    public Set getOrder1s() {
        return this.order1s;
    }
    
    public void setOrder1s(Set order1s) {
        this.order1s = order1s;
    }
   








}