package cn.myhotel.model;
// Generated by MyEclipse - Hibernate Tools



/**
 * Badman generated by MyEclipse - Hibernate Tools
 */
public class Badman extends AbstractBadman implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 8482083159815932386L;


	/** default constructor */
    public Badman() {
    }

    
    /** full constructor */
    public Badman(String name, String sex, String cardno) {
        super(name, sex, cardno);        
    }
   
}
