package cn.myhotel.model;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * Client generated by MyEclipse - Hibernate Tools
 */
public class Client extends AbstractClient implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = -206880836173479564L;

	/** default constructor */
    public Client() {
    }

	/** minimal constructor */
    public Client(String clientId, String password, String name, String sex, Date birth, String cardno, Date regdate, String type) {
        super(clientId, password, name, sex, birth, cardno, regdate, type);        
    }
    
    /** full constructor */
    public Client(String clientId, String password, String name, String sex, Date birth, String cardno, String tel, String address, Date regdate, String type, String isbad, String isused, Set order1s) {
        super(clientId, password, name, sex, birth, cardno, tel, address, regdate, type, isbad, isused, order1s);        
    }
   
}
