package cn.myhotel.model;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * News generated by MyEclipse - Hibernate Tools
 */
public class News extends AbstractNews implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = -8900869549511197189L;

	/** default constructor */
    public News() {
    }

	/** minimal constructor */
    public News(String title, String author, Date sendtime) {
        super(title, author, sendtime);        
    }
    
    /** full constructor */
    public News(String title, String author, Date sendtime, String content, String hot) {
        super(title, author, sendtime, content, hot);        
    }
   
}
