package cn.myhotel.model;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * Order2 generated by MyEclipse - Hibernate Tools
 */
public class Order2 extends AbstractOrder2 implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = -7196992112058715688L;

	/** default constructor */
    public Order2() {
    }

	/** minimal constructor */
    public Order2(Room room, String name, String sex, Date birth, String cardno, Date regdate, Double price, Integer datenum) {
        super(room, name, sex, birth, cardno, regdate, price, datenum);        
    }
    
    /** full constructor */
    public Order2(Room room, String name, String sex, Date birth, String cardno, String tel, String address, Date regdate, Double price, Integer datenum, String isused) {
        super(room, name, sex, birth, cardno, tel, address, regdate, price, datenum, isused);        
    }
   
}
