package cn.myhotel.model;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * Order1 generated by MyEclipse - Hibernate Tools
 */
public class Order1 extends AbstractOrder1 implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = -1056744074219969411L;

	/** default constructor */
    public Order1() {
    }

	/** minimal constructor */
    public Order1(Room room, Client client, Date regdate, Double price, Integer datenum) {
        super(room, client, regdate, price, datenum);        
    }
    
    /** full constructor */
    public Order1(Room room, Client client, Date regdate, Double price, Integer datenum, String isused, String done) {
        super(room, client, regdate, price, datenum, isused, done);        
    }
   
}
