/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.myhotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.myhotel.model.Client;
import cn.myhotel.model.ClientDAO;

import com.myhotel.struts.form.EdiclientForm;

/** 
 * MyEclipse Struts
 * 
 * XDoclet definition:
 * @struts.action path="/admin/addclient" name="ediclientForm" input="/admin/addclient.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/templates/message.jsp"
 */
public class AddclientAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		EdiclientForm ediclientForm = (EdiclientForm) form;// TODO Auto-generated method stub
		ClientDAO dao = new ClientDAO();
		String id = request.getParameter("id");
		Client client = dao.findById(Long.valueOf(id));
		client.setIsused(ediclientForm.getIsused());
		String mlink = "../admin/addclient.jsp?id="+id;
		String msg = "";
		if(dao.attachDirty(client))
			msg = "保存数据成功！";
		else
			msg = "保存数据失败！";
		dao.closeSession();
		request.setAttribute("msg", msg);
		request.setAttribute("mlink", mlink);
		return mapping.findForward("success");
	}
}