/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.myhotel.struts.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.myhotel.model.Room;
import cn.myhotel.model.RoomDAO;

/** 
 * MyEclipse Struts
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/templates/message2.jsp"
 */
public class AddcarAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String id = request.getParameter("id");
		RoomDAO dao = new RoomDAO();
		Room room = dao.findById(Long.valueOf(id));
		String msg;
		if(request.getSession().getAttribute("car")==null)
		{
			List list = new ArrayList();
			list.add(room);
			request.getSession().setAttribute("car", list);
			msg = "房间已成功添加到预订列表！";
		}
		else
		{
			List list = (List)request.getSession().getAttribute("car");
			int count = 0;
			for(int i=0;i<list.size();i++)
			{
				Room obj = (Room)list.get(i);
				if(obj.getId().toString().equals(id))
				{
					count = 1;
					break;
				}
			}
			if(count == 0)
			{
				list.add(room);
				msg = "房间已成功添加到预订列表！";
			}
			else
				msg = "你已经添加了该房间！";
			request.getSession().setAttribute("car", list);
		}
		request.setAttribute("msg", msg);
		return mapping.findForward("success");
	}
}