/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.myhotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.myhotel.model.Room;
import cn.myhotel.model.RoomDAO;
import cn.myhotel.model.Roomtype;

import com.myhotel.struts.form.AddroomForm;

/** 
 * MyEclipse Struts 
 * 
 * XDoclet definition:
 * @struts.action path="/bascitem/addroom" name="addroomForm" input="/bascitem/addroom.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/templates/message.jsp"
 */
public class AddroomAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddroomForm addroomForm = (AddroomForm) form;// TODO Auto-generated method stub
		RoomDAO dao = new RoomDAO();
		Room room = new Room();
		String mlink = "";
		String msg = "";
		if(request.getAttribute("room")!=null)
		{
			room = (Room)request.getAttribute("room");
			mlink = "../bascitem/addroom.jsp?id="+room.getId();
		}
		else
		{
			mlink = "../bascitem/addroom.jsp";
			room.setIsused("0");
		}
		room.setRoomId(addroomForm.getRoomId());
		room.setFloor(Integer.valueOf(addroomForm.getFloor()));
		Roomtype roomtype = new Roomtype();
		roomtype.setId(Long.valueOf(addroomForm.getTypeId()));
		room.setRoomtype(roomtype);
		if(dao.attachDirty(room))
			msg = "保存数据成功！";
		else
			msg = "保存数据失败！";
		dao.closeSession();
		request.setAttribute("msg", msg);
		request.setAttribute("mlink", mlink);
		return mapping.findForward("success");
	}
}