/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.myhotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.Globals;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import cn.myhotel.model.Admins;
import cn.myhotel.model.AdminsDAO;
import cn.myhotel.model.Client;
import cn.myhotel.model.ClientDAO;

/** 
 * MyEclipse Struts
 * 
 * XDoclet definition:
 * @struts.action input="/admin/changepwd.jsp" validate="true"
 * @struts.action-forward name="success" path="/templates/message.jsp"
 */
public class ChangepwdAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		ActionMessages messages = this.getMessages(request);
		String p1 = request.getParameter("rpas");
		String p2 = request.getParameter("pas");
		String type = request.getParameter("type");
		String mlink = "../admin/changepwd.jsp";
		String msg = "";
		if(type.equals("admin"))
		{
			Admins admin = (Admins)request.getSession().getAttribute("user");
			if(!admin.getPassword().equals(p1))
			{
				messages.add(Globals.ERROR_KEY,new ActionMessage("change.jiumima"));
				this.addErrors(request, messages);
				return mapping.getInputForward();
			}
			else
			{
				AdminsDAO dao = new AdminsDAO();
				admin.setPassword(p2);
				if(dao.attachDirty(admin))
				{
					request.getSession().setAttribute("user", admin);
					msg = "ÐÞ¸ÄÃÜÂë³É¹¦£¡";
				}
				else
					msg = "ÐÞ¸ÄÃÜÂëÊ§°Ü£¡";
				dao.closeSession();
			}
		}
		else
		{
			Client client = (Client)request.getSession().getAttribute("user");
			if(!client.getPassword().equals(p1))
			{
				messages.add(Globals.ERROR_KEY,new ActionMessage("change.jiumima"));
				this.addErrors(request, messages);
				return mapping.getInputForward();
			}
			else
			{
				ClientDAO dao = new ClientDAO();
				client.setPassword(p2);
				if(dao.attachDirty(client))
				{
					request.getSession().setAttribute("user", client);
					msg = "ÐÞ¸ÄÃÜÂë³É¹¦£¡";
				}
				else
					msg = "ÐÞ¸ÄÃÜÂëÊ§°Ü£¡";
				dao.closeSession();
			}
		}
		
		request.setAttribute("msg", msg);
		request.setAttribute("mlink", mlink);
		return mapping.findForward("success");
	}
}