/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.myhotel.struts.action;

import java.text.SimpleDateFormat;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.myhotel.model.Client;
import cn.myhotel.model.ClientDAO;

import com.myhotel.struts.form.ClientInfoForm;

/** 
 * MyEclipse Struts
 * 
 * XDoclet definition:
 * @struts.action path="/client/clientInfo" name="clientInfoForm" input="/client/clientInfo.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/templates/message.jsp"
 */
public class ClientInfoAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ClientInfoForm clientInfoForm = (ClientInfoForm) form;// TODO Auto-generated method stub
		ClientDAO dao = new ClientDAO();
		
		Client client = (Client)request.getAttribute("client");
		try{
			BeanUtils.copyProperties(client,clientInfoForm);
		}catch(Exception e){
			e.printStackTrace();
		}
		SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
		try{
			client.setBirth(df.parse(clientInfoForm.getDate1()));
		}catch(Exception e){
			e.printStackTrace();
		}

		String mlink = "../client/clientInfo.jsp?id="+client.getId();
		String msg = "";
		if(dao.attachDirty(client))
			msg = "保存数据成功！";
		else
			msg = "保存数据失败！";
		dao.closeSession();
		request.setAttribute("msg", msg);
		request.setAttribute("mlink", mlink);
		return mapping.findForward("success");
	}
}