/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.myhotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Session;
import org.hibernate.Transaction;
import cn.myhotel.model.Order2;
import cn.myhotel.model.Order2DAO;
import cn.myhotel.model.Room;

/** 
 * MyEclipse Struts
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/templates/message.jsp"
 */
public class Returnorder2Action extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String id = request.getParameter("id");
		String mlink = "../admin/order2.do";
		String msg = "";
		Order2DAO dao = new Order2DAO();
		Session session = dao.getSession();
		Order2 order2 = (Order2)session.load(Order2.class, Long.valueOf(id));
		boolean passed = false;
		try{
			Transaction tx = session.beginTransaction();
			order2.setIsused("1");
			Room room = (Room)session.load(Room.class, order2.getRoom().getId());
			room.setIsused("0");
			session.update(order2);
			session.update(room);
			tx.commit();
			passed = true;
		}catch(Exception e){
			passed = false;
			e.printStackTrace();
		}finally{
			session.close();
		}
		if(passed)
			msg = "操作成功！";
		else
			msg = "操作失败！";
		request.setAttribute("msg", msg);
		request.setAttribute("mlink", mlink);
		return mapping.findForward("success");
	}
}