/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.myhotel.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;

import cn.myhotel.model.RoomDAO;
import cn.myhotel.page.PageInfo;

/** 
 * MyEclipse Struts
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/bascitem/room.jsp"
 */
public class RoomAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		RoomDAO dao = new RoomDAO();
		PageInfo p = new PageInfo();
		String page = request.getParameter("Page");
		if(page==null||page.equals(""))
			page = "1";
		String hql1 = "select count(id) from Room";
		String hql2 = "from Room";
		if(request.getParameter("roomId")!=null)
		{
			hql1 = "select count(id) from Room where roomId = '"+request.getParameter("roomId")+"'";
			hql2 = "from Room where roomId = '"+request.getParameter("roomId")+"'";
		}
		Query query0 = dao.getSession().createQuery(hql1);
		p.setTotalcount(((Integer)query0.iterate().next()).intValue());
		p.setPageno(Integer.parseInt(page));
		Query query = dao.getSession().createQuery(hql2);
        
		query.setFirstResult(p.getFirstno());
		query.setMaxResults(p.getPagecount());
		List list = query.list();

        dao.closeSession();

		request.setAttribute("list", list);
		request.setAttribute("Totalcount", Integer.valueOf(p.getTotalcount()));
		request.setAttribute("Pageno", Integer.valueOf(p.getPageno()));
		request.setAttribute("Totalpage", Integer.valueOf(p.getTotalpage()));
		request.setAttribute("Pagescoll", Integer.valueOf(p.getPagescoll()));
		return mapping.findForward("success");
	}
}