/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.myhotel.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import cn.myhotel.model.Client;
import cn.myhotel.model.ClientDAO;
import cn.myhotel.model.Order2;
import cn.myhotel.model.Order2DAO;

/** 
 * MyEclipse Struts
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/admin/clientInfo.jsp"
 */
public class ShowclientAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String id = request.getParameter("id");
		String type = request.getParameter("type");
		if(type.equals("1"))
		{
			ClientDAO dao = new ClientDAO();
			Client client = dao.findById(Long.valueOf(id));
			request.setAttribute("client", client);
		}
		else
		{
			Order2DAO dao = new Order2DAO();
			Order2 order2 = dao.findById(Long.valueOf(id));
			request.setAttribute("client", order2);
		}
		return mapping.findForward("success");
	}
}